cofacts/rumors-site

pages/index.js

So let's make them short.
I originally used punctuation to shorten these up; but, too many rumors have too many crazy uses of punctuation. This seems like a decent compromise.

Rumor titles shouldn't be crazy long

---

components/App.js
pages/article.js

Implements #18.
This adds [`ClaimReview`](https://developers.google.com/search/docs/data-types/factcheck) for replied articles, and [`Website`](https://developers.google.com/search/docs/data-types/sitename) for all web pages.

Implements fact-check tag

---

pages/article.js

Fixes #29 .
In the end, we does sorting in API server ( see https://github.com/cofacts/rumors-api/pull/46 ), so we only handles automatic scrolling here:

Scroll to current reply section after new replies are added

---

components/ListPage.js
components/Pagination.js
pages/index.js
pages/index.styles.js
pages/replies.js
redux/articleDetail.js
redux/articleList.js
redux/auth.js
redux/index.js
redux/replyList.js
util/reducer.js

Related to #32.
**Reply list**
- - -
**Mine-only reply list for logged-in people**
- - -
- Barebone for reply list component
- Reply list data-loading logic
- Article list and reply list both inherits from `ListPage`, which implements all change handlers for filter / sorting.
- Move styles shared by Article list and reply list to `index.styles.js`
- Refactor render functions in article list to match reply list's implementation
- Remove `connect` on `<Pagination />` so that it can be also used in reply list
- Set / Read "isLoading" state for article list and reply list

Barebone for reply list

---

components/ListPage.js
components/Pagination.js
pages/index.js
redux/articleList.js

Changes:
1. Remove "Latest updated" sorting. It's basically equivalent to "Most recently asked", because `updatedAt` field in BE API never updates.
2. Make "Most recently asked" the default sorting mechanism. Reasons:
* It makes our homepage (article list) looks different upon every visit, making the site visitors aware of new articles & feel that this site is updated often.
* Veteran editors rely on "Most recently asked" sorting very much, so we can just make it default
* If an article is "Most asked" but is not answered yet, it must be so difficult that it scares new editors away. Sticking with "Most recently asked" makes their lives easier.
3. Make "Not replied yet" the default filter. Reasons:
* We used "all" as default filter several months ago because at that time, there are too few …

New filter / sorting defaults for article list

---

components/App/App.css
components/ExpandableText.js
components/ReplyConnection.js
pages/article.js
pages/reply.js
util/__tests__/__snapshots__/text.js.snap
util/__tests__/text.js
util/text.js

**DON'T MERGE: Should merge after  https://github.com/cofacts/rumors-site/pull/42**
* Refactors `linkify()` and `nl2br()` so that they can be cascaded and allows React element inputs
* Adds `target="_blank"` to out-going links in article & reply pages. Fixes #40 
* Adds "open new window" icon at the end of target-blank links.

Refactor word processors

---

components/ExpandableText.js
components/RelatedReplies.js
components/ReplyConnection.js
util/__tests__/__snapshots__/text.js.snap
util/__tests__/text.js
util/text.js

1. Make `traverseForStrings()` in `util/text` support `BREAK`
2. Implements `truncate()`, which truncates strings by length, and appends `moreElem` when truncation happens. This is the core of `<ExpandableText>`. (See `util/__tests__/__snapshots__/text.js.snap`)
3. Rewrite `<ExpandableText>` to leverage `truncate()`. Move `linkify()` and `nl2br()` to outside of `<ExpandableText>` implementation.

Refactor <ExpandableText>

---

components/RelatedReplies.js

When I was processing https://cofacts.g0v.tw/article/AV85NPHeyCdS-nWhuhya
there are a lot of related articles. Later I found an adequate reply inside. If the related article were to shown, it would help me identifying the related reply a lot.
This PR adds the article content above the reply, hoping that it provides good preview for the editors to better choose from existing replies.

Show content of the related article in related reply section

---

components/ReplyConnection.js
redux/articleDetail.js

This is merely an enhancement to fix the confusions I encountered when reading https://cofacts.g0v.tw/article/5489561179541-rumor#_=_ . Not mentioned in the meetings before.

Show reply’s original author and reply connection’s time in article page

---

pages/article.js
pages/article.styles.js

Related to #46.
"Search" tab is not included yet.

New reply tabs

---

components/RelatedReplies.js
pages/article.js
redux/__tests__/__snapshots__/articleDetail.js.snap
redux/__tests__/articleDetail.js
redux/articleDetail.js
redux/fixtures/articleDetail.js

Logic revamp:
1. Adding snapshot testing for `articleDetail` reducers. See snapshot files to check how the reducer work!
2. Simplify the logic of processing `relatedReplies`. Previously it inserts `articleId` twice and looking up article in `render()` functions. Now it is more straightforward, with `article` directly embedded.
3. Change related UI components. Removes unused props.
No UI change for this PR.

Refactor article detail

---

components/ReplyConnection.js

Currently, visiting this page will show 500:
https://cofacts.g0v.tw/article/AWF5zhDvhutQxxU6triN
The corresponding error log is:
```
site_1          | TypeError: Cannot read property 'get' of null
site_1          |     at ReplyConnection._this.renderAuthor (/srv/www/.next/dist/components/ReplyConnection.js:143:43)
site_1          |     at ReplyConnection.render (/srv/www/.next/dist/components/ReplyConnection.js:185:15)
site_1          |     at za (/srv/www/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:32:322)
site_1          |     at a.render (/srv/www/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:18)
site_1          |     at a.read (/srv/www/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:35:250)
site_1          |     at …
```

Better null handling for authors

---

components/ReplyConnection.js

Seems that `<style jsx>` is not scoped to each render function, but scoped to something larger instead. (React component I guess?)
This may lead to some confusion though. Styled-components would not have such issue, maybe we should consider that when applying the actual website theme.

Fix not-in-range info style scoping issue

---

components/Modal/index.js

I set body fixed and overflow hidden when modal open. But it makes search list hard to use, maybe should remove it...

remove overflow hidden and fixed from modal open

---

components/CurrentReplies.js
components/ReplyConnection.js
components/ReplyFeedback.js
ducks/__tests__/__snapshots__/articleDetail.js.snap
ducks/articleDetail.js
ducks/fixtures/articleDetail.js
ducks/replyDetail.js
ducks/replyList.js
jsconfig.json
pages/article.js
pages/reply.js

Make necessary changes to make the UI compatible with API after [201712-mappings-refactor](https://github.com/cofacts/rumors-api/pull/62).
Since we are having low test coverage in this repository, I am doing minimal changes to support the new API.
Please refer to [staging API site](https://cofacts-api.hacktabl.org) for the new API.
Future improvements should follow these steps:
1. We are having the new UI
2. Implement the new UI
3. Write tests on the new UI
Currently we are not plan to rename concepts/names like 'ReplyConnections' to new names (like "ArticleReplies") thoroughly from rumros-site codebase yet.
We will put that off until we have a new UI, then we will switch to the new name when we are doing UI revamp.

201712 mappings refactor

---

components/App/App.css
components/App/AppHeader.js
components/App/UserName.js
components/App/images/edit.svg
ducks/auth.js

- Allows editors to change names
- Adds "loading" state indicator for name display
- Moves `.hidden-xs` to `App.css` so that it can be used anywhere
Fixes #94

Editor name editing function

---

components/Modal/RepliesModal.js
components/RelatedReplies.js
components/ReplyConnection.js
components/ReplyItem.js
ducks/__tests__/__snapshots__/articleDetail.js.snap
ducks/articleDetail.js
ducks/fixtures/articleDetail.js
ducks/replyDetail.js
ducks/replyList.js
pages/reply.js

This PR removes all deprecated `replies.versions`.
After this we can finally remove the deprecated fields in rumors-api.

Remove reply version from all logic

---

components/App/UserName.js

As specified by #129 ,
Previously logging out may cause error (reproducible on [staging](https://cofacts.hacktabl.org/articles) now).
This PR fixes the issue by handling the case where the new `user` becomes null after logout.
After fix:

Fix level-up detection causing logout to fail

---

components/Hyperlinks.js
components/ReplyConnection.js
ducks/articleDetail.js
ducks/replyDetail.js
pages/article.js
pages/reply.js

Shows URL title & summary for article & reply.
Fixes #102 
With one broken link (page not accessible)

Url preview for aritcles and replies

---

components/Hyperlinks.js
ducks/articleDetail.js
ducks/replyDetail.js

Note: this PR depends on API change cofacts/rumors-api#106
Related to #102 .

Add image and handle error in URL previews

---

components/Hyperlinks.js

API server would return `null` for `hyperlinks` field for some articles.
Handle `null` in `<Hyperlinks>`
Connect localhost to production API server, can open the page that errors in production:

<Hyperlinks> prop null handling

---

pages/create.js

A place for editors to input rumors they saw elsewhere.
Currently the page `/create` is not shown publicly.

Implement a create-article page for editors

---

components/Hyperlinks.js

Shrank url image preview and paddings to fit mobile

---

components/Hyperlinks.js

Make it less wide by setting max-width css on `link` class.
**Before**
**After**

Make url preview less wide

---

components/CopyButton.js
components/ReplyConnection.js
package-lock.json
package.json

Allow users to copy reply contents of articles along with the page link to clipboard. Show tooltip beside the Copy button on success. Use template from [suggestion](https://www.facebook.com/photo.php?fbid=10213500185051777&set=pcb.2055948657970286&type=3&theater&ifg=1):
Issue https://github.com/cofacts/rumors-site/issues/62

Add "copy to clipboard" button to each reply

---

components/Trendline.js
pages/article.js
pages/article.styles.js

Fixes #111 
Google datastudio is slow...

Add 30-day LINE bot search trendline to article page

---

components/AppLayout/LoginModal.js
components/NewReplySection.js
components/ReplyFeedback.js
components/ReplyForm.js
components/ReplyRequestReason/ReplyRequestReason.js
pages/article/[id].js

- Introduce `<NewReplySection>`, which will be the functional component performing apollo hooks for "Create reply" (this PR), "use existing reply" (future PR) and "search" (future PR)
- Component structure:
- `[id].js` (article page)
- `NewReplySection.js` the 3-tab functional component doing apollo-hooks
- `ReplyForm.js` the "new reply" form
- `ReplyForm.js` no longer relies on its `onSubmit` returning a promise to clear the field. Instead, it exposes a public method `clear()` for its parent component to clear when reply submission succeeded. This API is similar to how HTML inputs are cleared.
During development, I found that the `merge()` in `[id].js` is actually causing issues. I tried to use `merge()` to merge `LoadArticlePage` and `LoadArticlePageForUser` operations; however, the …

Create new reply form

---

components/NewReplySection.js
components/RelatedReplies.js
pages/article/[id].js

This PR implements "existing reply" tab.
- Component hierarchy:
- `[id].js` - article page, loads related reply field
- `NewReplySection.js` - the functional component of "New Reply" tabs, handles all mutations. DIsplays number of relatedReplies in tab badge.
- `RelatedReplies.js` - the content of "Reuse existing reply" tab
- `<RelatedReplyItem>`: each related reply item
To avoid confusion, `NewReplySection`  now doesn't pass anything when invoking `onSubmissionComplete` callback, which is invoked by both "create new reply" and "connect existing reply". The article page does not need that data anyway.

Connect replies component

---

components/ArticleItem.js
pages/article/[id].js
pages/articles.js

Implements the similar article list of an article.
- Rename `ArticleItem` fragment to PascalCase to match the convention of other fragments

Similar article list in article page

---

components/ReplyItem.js
components/SearchInput.js
constants/replyType.js
i18n/zh_TW.po
package.json
pages/articles.js
pages/replies.js

Implements list of replies with apollo-client.
Component hierarchy:
- `replies.js` - the page. Corresponds to [articles.js](https://github.com/cofacts/rumors-site/blob/dev/pages/articles.js)
- `ReplyItem.js` - each reply. Corresponds to [`ArticleItem`](https://github.com/cofacts/rumors-site/blob/dev/components/ArticleItem.js) and [`ArticleInfo`](https://github.com/cofacts/rumors-site/blob/dev/components/ArticleInfo.js)

Reply list

---

components/ArticleReply.js
components/ReplyFeedback.js
lib/apollo.js
lib/fetchAPI.js

Deployed to https://cofacts.hacktabl.org/
This PR fixes:
- Correct `x-app-id` should be provided in GraphQL request headers so that current user can be recognized as author of new replies
- Handle the case when empty reply.user causes exceptions
We will be deploying this to production soon. Please try navigating pages and submit replies in https://cofacts.hacktabl.org/ to see if there are any unhandled exceptions, thanks!

Fix HTTP header & handle empty users

---

components/Pagination.js
lib/text.js
pages/article/[id].js
pages/articles.js
pages/reply/[id].js

Add title to list of reported messages reported by same author. This previously existed but was omitted in #164.
Refactor:
- Besides `truncate(elem, option)`, we implement additional, text-only `ellipsis(text, option)` for pure-text cases like HTML titles.
- Remove excessive "loading" from `<Pagination>` when no result is available

Message list reported by author with article id

---

components/UsedArticleItem.js
i18n/zh_TW.po
pages/reply/[id].js

This PR implements the "this reply also used" section, which was omitted in #175 and is useful when tracking similar messages.
Implementation reference:
https://github.com/cofacts/rumors-site/blob/pocky-day-gathering/pages/reply.js#L147-L170

Implement "This reply also used in" section

---

.env.sample
.gitignore
components/FeedDisplay.js
lib/apollo.js
package-lock.json
package.json
pages/api/articles/[feed].js
pages/articles.js
pages/index.js

This PR implements part of #170 
- Adds RSS endpoint: `/api/articles/rss2`, `/api/articles/atom1`, `/api/articles/json1`
- Each endpoint supports same URL query as article page. For instance, `/api/articles/rss2?q=&replyRequestCount=1&filter=solved` will present "solved" messages with 1 or more reply requests.
- Add "Subscribe to list" button to article list.
- Adds feed syndication to `<head>`
- Adds `PUBLIC_URL` to replace all hard-coded `https://cofacts.g0v.tw`, allowing different URL for each site
- Applies `MAX_KEYWORD_LENGTH` (100) to keywords, so that URL's won't be too long when searching for long messages.
- Staging site: https://cofacts.hacktabl.org/articles
- Live RSS URL: https://cofacts.hacktabl.org/api/articles/rss2?q=&replyRequestCount=1&filter=solved

RSS for article lists

---

.dockerignore
.env.sample
Dockerfile
README.md
ecosystem.config.js
package-lock.json
package.json
server.js

Currently, site-zh often goes to CPU 100% and becomes extremely slow; in the mean time, our Linode actually has multiple cores. Currently rumors-site only uses 1 core, if we leverage more cores, the CPU usage should hit 100% less often.
This PR:
- Adds a custom server that works exactly the same as `next start`
- Modifies `Dockerfile` so that it runs pm2 and loads the custom server script
- Enables cluster mode so that we can control number of processes using `WEB_CONCURRENCY` env var on docker container

Setup pm2 cluster mode on production

---

.env.sample
README.md
pages/_document.js

Currently we use different Google tag manager container ID for development, staging & production.
However, tag manager configurations are pretty complicated. This separation cannot make sure what we have tested on staging will ever work on production.
This PR exposes `GA_TRACKING_ID` from env vars to `dataLayer`, so that google tag manager can pick the variable up:
In this way, all environments can share the same GTM container ID, while keeping GA tracking ID different:

Sends PUBLIC_GA_TRACKING_ID to dataLayer

---

components/ArticleReply.js
components/Hyperlinks.js

This PR implements "CreateReply 不要等 url resolving，有時候還會出錯" function mentioned in [202200212 meeting](https://g0v.hackmd.io/AwNFa7L1QKiBPziTtYva0A#CreateReply-%E4%B8%8D%E8%A6%81%E7%AD%89-url-resolving%EF%BC%8C%E6%9C%89%E6%99%82%E5%80%99%E9%82%84%E6%9C%83%E5%87%BA%E9%8C%AF). It significantly reduces the time editors need to wait after submitting replies:
The editors can freely navigate away even when the spinner loading hyperlinks is still spinning. The hyperlinks will still be properly loaded on API server.
It is achieved by [changing API](https://github.com/cofacts/rumors-api/pull/147) so that it don't wait for hyperlink resolution, and perform polling if hyperlink is not loaded.
The requests in the chart:
1. `CreateReply` API, which creates reply & articleReply in article
2. `GetArticle` …

[Hyperlinks] support polling hyperlinks when hyperlinks are loading

---

next.config.js
package-lock.json

Fixes #208 .
React 16 [depends on](https://reactjs.org/docs/javascript-environment-requirements.html) `Set` and `Map`, which is not provided on old browswers like IE<11 or Chrome < 37. Despite their super low market share, some old phones are still using them, and hundreds of "Set is not defined" error is triggered every single day by these legacy browsers, eating up our Rollbar free quota:
While Next.js includes babel-preset-env which invokes core-js transformation, [dependencies in NPM modules are not polyfilled nor transformed](https://github.com/zeit/next.js/tree/canary/examples/with-polyfills). This is why simply adding `target: "default, chrome 33"` in babel config doesn't work.
In addition, some of our dependencies are depending on `Object.assign`, which does not exist on Chrome …

Add core-js polyfill in webpack

---

README.md
components/AppLayout/UserName.js
lib/useCurrentUser.js

According to Google analytics doc ["Handling authentication after pageload"](https://developers.google.com/analytics/devguides/collection/analyticsjs/cookies-user-id#handling_authentication_after_pageload) section, for applications that handles authentication after page load, we can set `userId` and then as following event fires, the whole session will have userId through [session unification](https://support.google.com/analytics/answer/4574780).
In Google Tag Manager we will load `CURRENT_USER` as variable and set it to Google Analytics setup.

Add CURRENT_USER to GTM dataLayer after user is logged in

---

components/ArticleItem.js

Currently visiting [article list](https://cofacts.hacktabl.org/articles) will see 500 internal server error:
The root cause is `ArticleItem` trying to read `createAt` on empty reply:
```
cofacts-staging-zh_1_26a0c24950d3 | 2020-03-05 06:04 +00:00: Error while running `getDataFromTree` TypeError: Cannot read property 'createdAt' of undefined
cofacts-staging-zh_1_26a0c24950d3 |     at ArticleItem (/srv/www/.next/server/static/RmJ6dlBKzFB7gLIxTollr/pages/articles.js:331:46)
```
Another bug is, when navigating to article page with existing reply, this error may come up:
```
'Store error: the application attempted to write an object with no provided ' +
'id but the store already contains an id of Reply:Hjq2E2UBbZnN2I-EOZtn for ' +
'this object. The selectionSet that was trying to be written …
```

Handle when latestReply is undefined

---

components/ReplyItem.js
constants/errors.js
lib/rollbar.js
pages/_document.js
pages/articles.js
pages/replies.js

Fixes #227  by
1. Display error and handle null values properly in article list page
2. ignore [that specific error](https://github.com/cofacts/rumors-api/blob/master/src/graphql/queries/ListArticles.js#L141) in Rollbar 
This PR also fixes #193 by properly handle null values in reply list page. Also, user ID and reply ID are added in query to avoid Apollo-client cache update failure.

Fixes searchUserByArticleId and reply page error

---

.env.sample
components/ArticleCategories.js
components/ArticleCategories/ArticleCategories.js
components/ArticleCategories/ArticleCategory.js
components/ArticleCategories/DownVoteDialog.js
components/ArticleCategories/index.js
components/ReplyFeedback.js
lib/apollo.js
pages/article/[id].js

Implements Article page UI in #213.
- List article categories under article text & reply request list.
- The person adding the category (`canUpdateStatus === true`) can remove category (has delete button)
- Clicking category label opens a dropdown that has options which
- links to article list under that category
- performs upvote and display upvote count
- If user has upvoted, the option will be disabled.
- opens downvote dialog, which displays others' reason of downvote and can fill in own downvote reason
- If user has downvoted, the dialog should include their own submitted reason. They can update their own reason by casting downvote again.
- "Add category" button is hidden by default. Shown only when env var `PUBLIC_SHOW_ADD_CATEGORY` is set.
Currently the API mock does not contain …

Category list in article page

---

components/ArticleCategories/AddCategoryDialog.js
components/ArticleCategories/ArticleCategories.js
components/ArticleCategories/ArticleCategory.js

Implements the interaction of "Add category" button as part of #213 .
- Dialog displays all categories
- Disallow user to add categories that is already added to the article
- Updates article's articleReply from API
Note: In the video above, after adding a category to the article, the list of categories has only the most recently added category left. This is wrong but it's the current behavior of the API mock. The real `CreateArticleCategory` implementation is expected to return a list of all currently added categories, including the most recently added category. cc/ @godgunman

Add category to article

---

components/AppLayout/AppHeader.js
lib/apollo.js

During SSR, an GraphQL Error can halt the processing of Apollo-link middlewares, causing the server-side render to return nothing.
This PR:
1. Always print error console whenever apollo-link-error callback is invoked.
- `console.error` works on both browsers and servers, and does not interrupt users at all, thus is a great choice to help with development
- We don't use rollbar here because this would also capture the case when user does mutation without logging in
2. Fix SSR by detecting if `alert` exists in the global namespace (it's `undefined` during NodeJS SSR)
3. Includes a minor fix that renames a GraphQL query to avoid naming collisions, which allows us better identifying GraphQL queries.
From discussion: https://g0v-tw.slack.com/archives/C2PPMRQGP/p1589437262448200?thread_ts=158866 …

Fix apollo-link-error causing SSR requests to halt

---

README.md
components/ArticleItem.js
components/ArticlePageLayout.js
components/ExpandableText.js
components/FeedDisplay.js
components/Filters.js
components/ReplyFeedback.js
components/ReplyItem.js
components/SortInput.js
components/TimeRange.js
lib/useCurrentUser.js

This PR sends the `data-ga` property or `displayName` of the clicked component to Google Analytics, so that we can track click of component of interest.
See the `eventCategory` (in non-bold text) on the right side of the screen recording:
Collected events in Google analytics:
This fixes #237 .
This PR implements "成效追蹤" part of the following spec:
- [Dubious messages](https://g0v.hackmd.io/ahtI6xsFRQyxktrIlc1VcQ#%E6%88%90%E6%95%88%E8%BF%BD%E8%B9%A4)
- [Latest replies](https://g0v.hackmd.io/ZZWHWi2BTuyhkSWzAvKLAw#%E6%88%90%E6%95%88%E8%BF%BD%E8%B9%A4)
- [Hoax for you](https://g0v.hackmd.io/@NFi0czulSemxCM8RNSlz8Q/HJ8xT3QVU/%2FN8I2-zkJTaS35BP8VH8ZQA) (subset of Latest replies)
This shows the the clicked item's component name (`<ComponentName>`) or `data-ga` property (`[ga propety]`) when …

Introduce data-ga and displayName in Google Analytics tracking

---

components/NewReplySection/index.js

Ref: https://www.facebook.com/groups/cofacts/permalink/2702689166629562/
All reply submission. No one can submit new replies to Cofacts now.
In `NewReplySection/index`, `handleSubmit` is picking up old `fields` variable, which is always empty.
- Add `fields` to `useCallback` deps
- TODO: Make eslint emit error on omitted dependency

[Hotfix] Fix reply form empty submission bug

---

.eslintrc.js
components/AppLayout/AppLayout.js
components/AppLayout/GlobalSearch.js
components/AppLayout/UserName.js
components/ArticlePageLayout.js
components/ArticleReply/CopyButton.js
components/ArticleReply/ReplyShare.js
components/ArticleReply/index.js
components/CreateReplyRequestForm/CreateReplyRequestForm.js
components/ExpandableText.js
components/Filters.js
components/NewReplySection/ReplyForm/context.js
components/NewReplySection/ReplySearch/ReplySearch.js
components/NewReplySection/index.js
components/ReplySearchItem.js
components/ReplySearchPageLayout.js
components/TimeRange.js
lib/gtm.js
lib/useCurrentUser.js
package-lock.json
package.json
pages/article/[id].js
pages/instant.js
pages/reply/[id].js
pages/search.js

This PR enables react-hooks eslint rules and fixes all errors.
All violation of `react-hooks/exhausive-deps` now triggers build failure and requires explicitly disabling it using line comments (also need to include a good reason in comment!).
Current violations are fixed using the following rules:
-  `useCallback`:
1. curried callbacks (`item => () => {}`) should not put in `useCallback` because when it's used in event handlers, curry function is invoked and a new copy of handler is always returned. There is no use putting `useCallback` over curried callbacks.
2. event handlers depending on other function that is not memoized: its dependency will change every render. I remove its `useCallback` in this case.
3. otherwise, add dependency to array. 
- `useEffect`:
1. If it's meant to be a …

Enable react hook lint rules

---

.babelrc.js
.storybook/main.js
Storyshots.test.js
__snapshots__/Storyshots.test.js.snap
components/Example.stories.js
components/TimeRange.js
components/TimeRange.stories.js
components/__snapshots__/TimeRange.stories.storyshot
jest.config.js
package-lock.json
package.json

Adds storybook & storyshot for `<TimeRange>` component.
- Enzyme is required because `react-test-renderer` storyshot built-in cannot handle `Material-UI`'s portal (used in Material UI Modal that comprised of Material UI dropdown lists). Ref: https://github.com/storybookjs/storybook/tree/master/addons/storyshots/storyshots-core#renderer
- Adds `@storybook/addon-knobs` to demonstrate how `<TimeRange />` reacts to `range` prop change
- Removes brittle snapshot made by Material-UI internals by [implementing enzyme-to-json `map` function](https://github.com/adriantoine/enzyme-to-json/blob/master/docs/map.md)
- Splits snapshot files into one snapshot per story file (but currently there is only 1 story so far...) using `multiSnapshotWithOptions` and [corresponding …

Storybook for TimeRange

---

Storyshots.test.js
components/ListPage/__snapshots__/BaseSortInput.stories.storyshot
components/ListPage/__snapshots__/BaseTimeRange.stories.storyshot
components/ListPage/__snapshots__/Filters.stories.storyshot
components/ListPage/__snapshots__/LoadMore.stories.storyshot
components/PlainList.js
components/__snapshots__/ExpandableText.stories.storyshot
components/__snapshots__/PlainList.stories.storyshot

`makeStyle`'s serial number in classnames often cause storyshots to change as we write new stories, resulting in irrelevant code changes in pull requests.
This PR:
- removes the serial number from snapshots
- supports `makeStyle` and `MuiBox`
- This makes snapshots more independent from each other.
- replaces `withStyle` with `makeStyle` for components in storyshot
- The snapshot of `withStyle` is difficult to modify, thus change to use the latter.
- updates all snapshots

[Trivial] Remove serial number from makeStyle className in storyshots

---

components/ArticleCategories/CategoryOption.js

As discussed in 0722, we are going to let collaborators try out our category UI in the hackathon tomorrow. 
In order to properly display the [category definition](https://g0v.hackmd.io/D4KfdMRWS-OmCKd-Fhli2Q), we add line breaks to make descriptions more readable.

Add line breaks to category description

---

components/NewReplySection/ReplyForm/ReferenceInput.js
components/NewReplySection/ReplySearch/SearchBar.js

Done
搜尋框加上「參考過往回應」的 placeholder
使理由與來源的 input 能垂直拉大
增加搜尋圖示提供搜尋功能，而不是只能用 Enter
TODOs
使理由與來源的 input 水平方向則固定
搜尋時加上 loading indicator
修正 iOS 點按「Add this reply to my reply」送出的問題

Add search icon, placeholder, and enablef height adjustment

---

components/AppLayout/AppHeader.js
components/AppLayout/GlobalSearch.js

Prevent search input from being hided

---

components/ArticleInfo.js

ArticleInfo should query for articleReplies as it is using articleReply data.
Staging:
Localhost:
Detail page can load without problem
`<ArticleInfo>` in `ArticleDetail` page actually uses `articleReplies` field. However, It's not declared in its fragment, thus `articleReplies` fields are not populated properly in detail page.
This PR adds the field in loading sequence so that the field exists no matter where `<ArticleInfo>` is used.

Fix dev "cannot invoke map of undefined" bug

---

components/ArticleInfo.js
components/Infos/Infos.js
components/Infos/Infos.stories.js
components/Infos/TimeInfo.js
components/Infos/__snapshots__/Infos.stories.storyshot
components/Infos/index.js
components/ReplyInfo.js
package.json

This PR implements `<Infos>` and `<TimeInfo>` and reuse them in `<ArticleInfo>` and `<ReplyInfo>` temporarily.
Actually, in the mockup the info lines are very diverse and has different info to display in each place.
In the future,  `<ArticleInfo>` and `<ReplyInfo>` will be removed, and `<Infos>` and `<TimeInfo>` will be directly used in article items instead.

Introduce <Infos> and <TimeInfo> for as a flexible info display

---

package-lock.json
package.json
pages/_app.js

According to #313 we should support Safari >= 10.3; however, currently our usage of `Object.fromEntries` breaks iOS safari.
This PR:
- Removes unused babel preset (they are already [included in Next.js 9.3](https://nextjs.org/blog/next-9-3#32-kb-smaller-runtime-15-kb-gzip))
- Adds `core-js/features/object/from-entries` to `_app.js`
- putting polyfill in `_app` is the suggested way of adding custom polyfills in [official doc](https://nextjs.org/docs/basic-features/supported-browsers-features#custom-polyfills)
- [`nomodule` trick](https://3perf.com/blog/polyfills/) can't be used because iOS 11 supports nomodule (don't load nomodule scripts) but still does not support `Object.fromEntries` and needs to be polyfilled.
Fixes #313 .

Add Object.fromEntries polyfill to support iOS Safari 11

---

pages/search.js

Currently staging build fail because `/search` page is using a runtime config.
According to [next.js doc](https://nextjs.org/docs/api-reference/next.config.js/runtime-configuration):
> A page that relies on publicRuntimeConfig must use getInitialProps to opt-out of Automatic Static Optimization. Runtime configuration won't be available to any page (or component in a page) without getInitialProps.
We should pass `{ssr: true}` to `withApollo` so that next-apollo attaches [`getInitialProps`](https://github.com/adamsoffer/next-apollo/blob/master/src/withApollo.js#L108) to search page and thus opt-out Automatic Static Optimization for `/search` page.

Make production build works by opt-out static build for search pages

---

.storybook/preview.js
components/AppLayout/AppFooter.js
components/AppLayout/AppHeader.js
components/AppLayout/AppSidebar.js
components/AppLayout/GoogleWebsiteTranslator.js
lib/theme.js
pages/_app.js
pages/_document.js

Currently in iOS system, Google translate will show toolbar no matter user has interacted with Translate widget or not, which covers up screen, especially for create reply dialog.
This PR:
- Initiates Google translate setup only after the user clicks "Google translate" button
- Fixes hover & ripple effect of button / list item by providing a [dark theme](https://material-ui.com/customization/palette/#dark-mode)
- Adjust sidebar style
- No translate toolbar at first; translate widget replaced with a "Google translate" button.
- As soon as the user clicks "Google translate" button, Google site translate loads and toolbar is added
The dark theme turns hover effect brighter (currently in production it darkens on hover, which is incorrect). The dark theme is required for `<Button …

Remove Google translate toolbar by loading Google site translate after click

---

components/ArticlePageLayout.js

Removes weird `replyRequestCount` setup because it is causing errors if an user is visiting Cofacts with legacy URL (with `replyRequestCount` in its URL, such as `https://cofacts.org/articles?q=ooo&replyRequestCount=1`)
Also, it does not make sense to set `filterObj` without any condition. The line overrides the `replyRequestCount` filter set by `FILTERS.ASKED_MANY_TIMES`, thus it must be removed for `ASKED_MANY_TIMES` to work properly.

Remove weird replyRequestCount setup

---

components/AppLayout/Widgets/Avatar.js
components/ArticleReply/index.js
components/ArticleReplyFeedbackControl/ArticleReplyFeedbackControl.js
components/ArticleReplyFeedbackControl/ArticleReplyFeedbackControl.stories.js
components/ArticleReplyFeedbackControl/Feedback.js
components/ArticleReplyFeedbackControl/ReasonsDisplay.js
components/ArticleReplyFeedbackControl/__snapshots__/ArticleReplyFeedbackControl.stories.storyshot
components/ListPageDisplays/ReplyItem.js
components/__snapshots__/ExpandableText.stories.storyshot

- extract reasons dialog to individual component
- load reply & feedbacks only when reasons dialog is open
- this reduces `ArticleReplyFeedbackControlData` fragment a lot, make `ArticleReplyFeedbackControl` a lot lighter on initial page load
- loads 100 feedbacks from new API `ListArticleReplyFeedbacks` that fetches articlereplyfeedbacks directly
- still show feedback for null users (usually from LINE; fixes #291 )
- removes `reply` prop from `ArticleReplyFeedbackControl`
- So the component props are simpler
- Loads reply text only when reasons dialog is open

Reasons dialog in <ArticleReplyFeedbacks> component

---

components/Subscribe/FeedDisplay.js
package-lock.json
package.json
pages/api/articles/[feed].js

Fixes #222 
1. Track subscriber number by sending event: 
Event Category: RSS
Event Action: Subscribe
Event Label: `Source`(Feedly, Feedrabbit, IFTTT)
Document title: [response header](https://www.petefreitag.com/item/418.cfm)
Document path: query variables
- Sends subscriber number when subscribing.
- Will cache the feed, it triggers the event when first time fetches the feed, and then each regular fetching(maybe [once an hour](https://www.feedly.com/fetcher.html)).
- Sends subscriber number each regular fetching.
- Triggers the event every time.
2. Track article page through google tag manager by adding `utm_source` 
`utm_source`: `Source`(Feedly, Feedrabbit, IFTTT)
`utm_medium`: RSS
1. Copy URL function shouldn't encode URL
Page title: res.header (subscriber number), Page path: query …

Track rss, and add utm_source to each url that generated from feed.js

---

components/ArticlePageLayout.js
components/ListPageControls/BaseSortInput.js
components/ListPageControls/BaseTimeRange.js
components/ListPageControls/Filters.js
components/ListPageControls/Tools.js
components/ListPageControls/Tools.stories.js
components/ListPageControls/__snapshots__/BaseTimeRange.stories.storyshot
components/ListPageControls/__snapshots__/Tools.stories.storyshot
components/ListPageDisplays/ListPageHeader.js
components/ListPageDisplays/ListPageHeader.stories.js
components/ListPageDisplays/__snapshots__/ListPageHeader.stories.storyshot
components/ReplyRequestReason/ReplyRequestReason.js
components/ReplySearchPageLayout.js
pages/article/[id].js

- Adjust page header's margins and font size so that it matches [the design](https://www.figma.com/file/zpD45j8nqDB2XfA6m2QskO/Cofacts-website?node-id=79%3A9)
- `<Tools>`
- hosts controls like `TimeRange` and `SortInput`
- in mobile, all controls are stacked and have the same width
- on desktop, all controls are laid out horizontally
- `<ListPageHeader>`
- layout title text and other items horizontally
- adjust font size on mobile and desktop
- Adjustments are made to `BaseTimeRange` and `BaseSortInput` so that they have same size and relax their width to work with `<Tools>`
Their width are now controlled by its container, thus shows 100% width in storybook

Layout components for header

---

components/ArticleReply/index.js
pages/article/[id].js

Closes #339.
- Add `在 LINE 看到可疑訊息？加「真的假的」好友，查謠言與詐騙` after copying text from article detail page
- Add "LINE 機器人 查謠言詐騙" floating action button
- Enlarge number of lines to display for reply text to reduce the need of clicking "Expand" button

Add instructions to add LINE as friend in article detail page

---

Storyshots.test.js
components/Card.js
components/Card.stories.js
components/Infos/__snapshots__/Infos.stories.storyshot
components/Ribbon.js
components/__snapshots__/Card.stories.storyshot
components/__snapshots__/Ribbon.stories.storyshot

This PR introduces `<Card>`, a common layout that can be seen in [article detail](https://www.figma.com/file/zpD45j8nqDB2XfA6m2QskO/Cofacts-website?node-id=1273%3A176), and will be applied to [reply detail](https://www.figma.com/file/zpD45j8nqDB2XfA6m2QskO/Cofacts-website?node-id=912%3A190) and [profile page](https://www.figma.com/file/zpD45j8nqDB2XfA6m2QskO/Cofacts-website?node-id=912%3A385) in the future.
Also I add I add `forwardRef` to `Card` and `Ribbon` because in future PRs we are going to need them.
In the design, the card has so many different appearances.
- They share the same mobile & desktop padding, so these styles should be shared
- But in some cases there are different headers or full-width footer buttons that don't respect the paddings.
Therefore the design of components …

<Card> for detail pages

---

.storybook/preview.js
__mocks__/styleMock.js
components/ArticleReplyFeedbackControl/ArticleReplyFeedbackControl.js
components/app.css
jest.config.js
lib/theme.js

This PR adjusts Material-UI theme used theme in Cofacts to better match [figma](https://www.figma.com/file/zpD45j8nqDB2XfA6m2QskO/Cofacts-website?node-id=681%3A0)
- Global border radius raised to 8px (default 4px)
- This affects dropdowns, pop-overs, snackbars, etc.
- Remove incorrect primary dark / light color setup
- The incorrect setup causes buttons in primary color turns grey when hovering on the button
- Remove the color so that Material-UI can handle hovering color by themselves.
- Set primary button text color in global CSS
- Material-UI uses `rgba(0,0,0,0.88)` by default
- Set to #fff to match [figma](https://www.figma.com/file/zpD45j8nqDB2XfA6m2QskO/Cofacts-website?node-id=890%3A586)
- Apply app.css to Storybook to reflect this change
- Use Material-UI `Button` in …

Adjust global border-radius and primary color palatte

---

pages/article/[id].js

Rewrite "similar messages" side section.
- Figma: https://www.figma.com/file/zpD45j8nqDB2XfA6m2QskO/Cofacts-website?node-id=890%3A585
- Mobile / desktop differs a lot, thus `Card` cannot be reused here.
- use explicit class name for each component in the similar messages section
- Fix firefox similar message section

Similar messages side section in article detail

---

components/AppLayout/AppHeader.js
components/AppLayout/AppLayout.js
components/AppLayout/AppSidebar.js

Before the 10/24 hackathon I would like to add a very simple edit name function, so that editors can change their display name as they wish.
Also fixes logout in mobile menu.
Also deployed to staging site for preview.

Makeshift edit name function for the hackathon

---

components/LandingPage/Header.js
components/LandingPage/SectionArticles.js
components/LandingPage/SectionCanDo.js
components/LandingPage/SectionContribute.js
components/LandingPage/SectionHow.js
components/LandingPage/SectionJoin.js
components/LandingPage/SectionNews.js
components/LandingPage/Stats.js
i18n/zh_TW.po

- Updates translation -- kudos to Kevin for the [revised translation](https://docs.google.com/spreadsheets/d/1Y2ag7xK5Hd-tdkfR1mde43a0EPw_SWXH-Pe2GQrdWU4/edit?usp=drive_web&ouid=100298319366825427383)!
- Fixes the first two items in [未竟之處](https://g0v.hackmd.io/@mrorz/cofacts-meeting-notes/%2F0RX4MsjRRJmBqJSKVilWMA) in 20210106 meeting
- Make all links in header to be an <a> tag and hide their underline until mouse hover
- Use Material UI `Button` to eliminate the underline button in landing page body
- `Navbar` background turns white on desktop when scrolled to the next section as expected
Note: Google chrome's screenshot mechanism does not trigger scroll events, thus enter animations are not triggered
Note: Google chrome's screenshot mechanism does not trigger scroll events, thus enter …

Update landing page copy & fix styles

---

components/AppLayout/AppHeader.js
components/AppLayout/AppLayout.js
components/AppLayout/AppSidebar.js
components/ProfilePage/EditProfileDialog.js
components/ProfilePage/ProfilePage.js
components/ProfilePage/UserPageHeader.js

This feature doesn't have figma.
- Allows user to edit display name, username (in URL), and bio.
- Updates UI after edit
- When the user have a slug (or updates a slug), redirect to URL with slug (`/user/[slug]`)
- App menu should always show progress bar as [in figma](https://www.figma.com/file/zpD45j8nqDB2XfA6m2QskO/Cofacts-website?node-id=0%3A1)
- remove the makeshift rename function introduced in #352 
Notice the URL changes as we save the new slug.

[Profile-04] Edit profile dialog

---

components/Hyperlinks.js
components/ProfilePage/ProfilePage.js
components/ProfilePage/RepliedArticleTab.js
components/ProfilePage/Stats.js
components/ProfilePage/UserPageHeader.js

- Implements "Replied article" tab in Profile page
- [Figma](https://www.figma.com/file/zpD45j8nqDB2XfA6m2QskO/Cofacts-website?node-id=3752%3A444)
- Supports filtering & sorting
- Known issue: `?slug=xxx` will be included in URL when filtering & sorting for users with slug.
- Move statistics data loading up, from `Stats` to `ProfilePage`
- As tabs will also include number of replied articles / feedback etc, we should load once in `ProfilePage` and pass down
- Refactor: fix `line-clamp` on Firefox
- `line-clamp` requires `display: -webkit-box`. The `-webkit` prefix is mandatory even on Firefox.

[Profile-06] Replied messages in profile page

---

components/ArticleReply/ArticleReply.js
components/ArticleReplyFeedbackControl/Feedback.js
components/ArticleReplySummary.js
components/ProfileLink.js
components/ProfilePage/RepliedArticleTab.js
components/__snapshots__/ArticleReplySummary.stories.storyshot
components/__snapshots__/ProfileLink.stories.storyshot
pages/reply/[id].js

In response to [Pilot Study suggestions](https://g0v.hackmd.io/XvP4q3IkTwCDeT1zopaTQg#%E5%BB%BA%E8%AD%B0), we should first keep profile pages to editors themselves for a few moments before opening it up to the public.
This PR:
- Temporarily remove `hasLink` from `<Avatar>`s
- Temporarily use `ProfileTooltip` instead of `ProfileLink` for public places
- App menu still uses `ProfileLink`, so that editors can click to their own profile page from main menu
This PR is deployed to staging temporarily for testing

Make profile page accessible for editors themselves only

---

.babelrc.js
components/NewReplySection/ReplyForm/ReasonEditor.js
i18n/zh_TW.po

with a little change in `.babelrc` https://github.com/cofacts/rumors-site/pull/383/commits/0be1cfa20929f6f3851016edb6d36d12d2fdd73e

enhance: #361 change placeholder and translate

---

pages/article/[id].js

Avoid attaching text for logged in users so that editors' copy-paste works better.
Fixes #350.
Copied text will have footer text attached.
Copied text will contain the selected text only.

Avoid attaching text for logged in users

---

components/LandingPage/SectionContribute.js
components/LandingPage/SectionJoin.js

"I want to learn how to use Cofacts" --> check hoax tutorial
"I can help bust hoax" --> bust hoax tutorial
"Count me in" --> bust hoax tutorial

[LandingPage] change links to tutorial instead

---

pages/impact.js

As discussed with @bil4444 we want to move report page URL from `/report` to `/impact`
- This URL is year neutral; can re-use every year
- Means "social impact", which is more specific than "report"

Move report page to /impact

---

pages/impact.js

Currently on production, the GA environment variable is not set. Therefore, no traffic to /impact is being captured by Google Analytics at all.
This PR fixes the issue by disabling build-time optimization so that runtime env variables can be picked up.

Make impact page server-rendered for GA env vars

---

components/Infos/TimeInfo.js
components/Infos/__snapshots__/Infos.stories.storyshot
components/Infos/__tests__/TimeInfo.js
components/ListPageDisplays/__snapshots__/ListPageCards.stories.storyshot
pages/article/[id].js

Thanks to @kerrickstaley we are now having relative dates!
This is a revision of the relative time display so that the behavior is more similar to Facebook timeline.
- Apply `TimeInfo` for "First reported" display on top right corner in article detail page
- Remove time from absolute time display outside of tooltip
- Align with Facebook timeline
- Relative date cut-off time changes to 48 hours
- Allows "yesterday" to appear
- Also allows literal "days ago"
- Calculate calendar days for relative date
- Calendar days should be more intuitive for users
- Replace "less than a minute ago" with seconds so that we don't need to translate lol
- Adds unit test for `formatDate()`
- Please check if the snapshot makes sense / is intuitive for users @bil4444

Revise time representation

---

components/ProfilePage/EditProfileDialog.js
components/ProfilePage/ProfilePage.js

Currently slugs with characters will trigger infinite page reload.
This PR modifies the reload detection mechanism so that it handles URL encoded paths correctly.

[ProfilePage] fix slug infinite redirect

---

components/ProfilePage/EditProfileDialog.js

Show snack when edit profile dialog errors.

Show error for EditProfileDialog

---

components/Infos/TimeInfo.js
i18n/zh_TW.po

Fixes #426.
- When `Intl.RelativeTimeFormat` is available, use it.
- It provides better strings like "yesterday", "前天"
- Otherwise, fallback to date-fns v2

Fix when Intl.RelativeTimeFormat is not available

---

components/WonderCallEmbed.js
pages/_app.js

- Implement `WonderCallEmbed` that loads iframe in a tooltip activated by a FAB
- Shows loading until iframe is fully loaded
- The FAB is not included in server-side rendering
Email:

Embed Wondercall in Cofacts

---

README.md
components/LandingPage/SectionCanDo.js
components/LandingPage/SectionNews.js
components/LandingPage/Stats.js
hooks/build
hooks/push
i18n/ja.po

- Include Japanese translation in codebase
- Build & push script
- Relax landing page style so that it also works for Japanese version
Deployed to: https://ja.cofacts.tw/

Japanese version

---

components/LandingPage/SectionArticles.js

Currently the landing page only shows messages that has no useful replies yet.
This may give new comer an initial impression that all messages are not getting replied in this website.
1. Include messages that is being replied in landing page.
2. List only articles with 3 or more reply requests, so that
- replied articles are not pushed down so fast
- it is more likely the message is seen by new site visitors, intriguing them to enter website
3. Sort by `createdAt` instead of `lastRepliedAt` so that replied articles are not pushed down by new requests.

[LandingPage] include messages that has been replied

---

components/ReportPage/EcosystemModal.js
components/ReportPage/SectionSponsor.js
constants/urls.js

Since we are using cofacts.tw as primary URL, we should change the legacy URLs in the codebase to cofacts.tw.

[Trivial] Update URL constants

---

lib/__tests__/__snapshots__/text.js.snap
lib/text.js

Currently when we copy links from "References" directly, we often copy the URLs with ellipsis in the middle, thus breaks the links.
This PR adjusted how ellipsis URLs are rendered so that when user selects the text and press "copy", the full URLs are copied instead.
Technically it is replacing `slice` + `...` with rendering the full URL + ellipsis with CSS.
Notice that the "..." in the URLs are gone when pasted.

Make ellipsis URLs copyable

---

README.md
components/NewReplySection/index.js
i18n/zh_TW.po

Fixes #449 
When reply text is empty or contains nothing but only space / line breaks, block submission.

Block empty replies

---

pages/_document.js

[Previous image build](https://github.com/cofacts/rumors-site/actions/runs/1529029608) fails due to the server-side cookie logic introduced in #457 .
This PR fixes the build by properly handle SSG case, which will have undefined ctx.req.

Handle SSG case

---

components/NewReplySection/ReplyForm/ReasonEditor.js
components/NewReplySection/ReplyForm/ReferenceInput.js

Extends #460 to fix reference input quirks & textarea borders on tablet size.

NewReplySection border & display fix

---

components/AppLayout/AppFooter.js
components/AppLayout/AppHeader.js
components/AppLayout/AppSidebar.js
components/LandingPage/Header.js

Discussion: https://g0v.hackmd.io/@mrorz/cofacts-meeting-notes/%2F-G9Md9IyQauRoalIXJgenQ 
This PR replaces the original "Forum" link in app header & app sidebar to tutorial.
- Landing page: "Forum" link changed to "Tutorial" and point to how-to-check-rumors tutorial (`/tutorial?tab=check-rumors`)
- Inside application: "Forum link" in app header & sidebar changed to "Tutorial" pointing to fact-checking tutorial.
- Add tutorial link to footer. (`/tutorial`)

[AppLayout][LandingPage] change forum links to tutorial

---

components/NewReplySection/ReplyForm/ReasonEditor.js
i18n/zh_TW.po
pages/article/[id].js

Fixes #463 , plus some missing translations.
No extra hint when there is no reply
Hint user to not reply other's reply when there is another reply
`Tutorial` in app header
Header of comment section `Comments from people reporting this message`

Tell editors to not reply other's reply + translations

---

components/ArticleReplyFeedbackControl/ReasonsDisplay.js
pages/article/[id].js

Depends on API: https://github.com/cofacts/rumors-api/pull/262
This PR implements M3:
- In the new API it will not show blocked content by default
- This PR allows blocked user to see blocked content (reply request, article reply, article category, article reply feedbacks) on article page
Note: there is 1 scammer comment in the image -- we forgot to ban the user previously. Block them here: https://github.com/cofacts/takedowns/pull/35/files?short_path=bcf97d9#diff-bcf97d9ee9386930d59f50144c9d0d8d90dbbeb775a27af646d41729cc055c80
All blocked contents are shown if and only if the browser is owned by a blocked user.
Ask API to query blocked feedbacks

Show blocked content only for blocked users

---

pages/reply/[id].js

See analysis in https://github.com/cofacts/rumors-site/issues/468#issuecomment-1005867982 
Fixes #468 .
Reply detail page of deleted reply will trigger internal server error:
Deleted reply can be properly displayed
Blocked reply (spam content) can be displayed in a minimalist fashion for public display, but do not allow web crawler to index
(Simulated by forcefully enter if statement)

[Reply] reply detail page should work for DELETED & BLOCKED content

---

components/ActionMenu/ActionMenu.js
components/ActionMenu/ActionMenu.stories.js
components/ActionMenu/__snapshots__/ActionMenu.stories.storyshot
components/ActionMenu/index.js
components/ArticleReply/ArticleReply.js
components/ArticleReply/ReplyActions.js
components/CurrentReplies.js
components/Infos/__snapshots__/Infos.stories.storyshot
components/ReportPage/__snapshots__/ActionButton.stories.storyshot
components/__snapshots__/ContributionChart.stories.storyshot
pages/reply/[id].js

- Extract `ActionMenu` (menu with vertical "⋯" button) from `ReplyActions`
- We will be adding that to reply requests and article reply feedbacks, thus extracting them will be beneficial
- Apperance adhere to https://www.figma.com/file/zpD45j8nqDB2XfA6m2QskO/Cofacts-website?node-id=1019%3A89
- Replace verbose props of `ReplyAction` to one single `articleReply`
- Previously there is an insane prop drill of `actionText`, `disabled` & `onAction` props from `CurrentReplies` & `reply/[id]` all the way down to `ReplyAction`
- However, all it needs to perform action is a article-reply instance.
- Minor behavior change: after restoring a reply from "Deleted replies" dialog, the dialog will not close automatically if there are still other deleted replies. I think this behavior is OK for the users. …

Implement ActionMenu and refactor article replies

---

components/NewReplySection/ReplyForm/ReasonEditor.js
components/NewReplySection/ReplyForm/ReferenceInput.js
i18n/zh_TW.po

As discussed in weekly meeting, we changed more Cofacts to 真的假的 in the Mandarin UI for better branding.

Make 真的假的 more prominant in zh locale

---

constants/urls.js

Now only 2 pre-filled fields left.

Shrink userId, itemId and url into 1 field only when reporting user

---

components/ArticleCategories/DownVoteDialog.js

Fixes #486. Root cause please see https://github.com/cofacts/rumors-site/issues/486#issuecomment-1125673951 .
I roughly checked other return value of `useQuery()`; other access of `data` prop are all properly guarded by `?.`.

Fix downvote dialog by proper null handling

---

pages/article/[id].js

Currently after up-voting or down-voting a reply, the whole article page will become "Loading...".
It seems that in @apollo/react-hooks v3.1.5 the `loading` state behavior is slightly different from 3.0.
This PR avoids "Loading..." page after an article is already displayed on screen.

Don't show loading if article is already loaded

---

components/ListPageDisplays/ArticleCard.js
components/ListPageDisplays/ListPageCards.js
components/ListPageDisplays/ListPageCards.stories.js
components/ListPageDisplays/ReplySearchItem.js
components/ListPageDisplays/__snapshots__/ListPageCards.stories.storyshot
components/NewReplySection/Mobile.js
components/ProfilePage/RepliedArticleTab.js
components/RelatedReplies.js
components/ReportPage/__snapshots__/ActionButton.stories.storyshot
pages/article/[id].js
pages/replies.js
pages/reply/[id].js
pages/search.js

Extends #490 on task #483 . Must merge after API PR https://github.com/cofacts/rumors-api/pull/288 is deployed.
This PR:
- Uses "thumbnail" variant for list
- Uses "preview" variant for detail page
- Constraints image height so that image articles does not take too much vertical space in lists
- In article detail, add link to original file for logged in users
Deployed to staging.
Note that only when user logs in, clicking the image in article detail would bring user to the original file

Support attachment variants

---

components/LandingPage/Header.js

The issue is found in [20220706 meeting](https://g0v.hackmd.io/UopCx5bcRb-gt_3SdVqRdQ#%E5%B0%8F%E8%81%9A%E7%B1%8C%E5%82%99)
Currently on production, if the user is already logged in, starts their session on the landing page, and then goes to other pages, their user ID will not be sent in Google Analytics actions.
This is because
- We push current user to Google Tag Manager in `useCurrentUser`'s `onCompleted` callback 
- Before this PR, landing page uses its own way to load user, and thus does not use `useCurrentUser`
- Landing page loads all fields that is required by `useCurrentUser`, so that when user enters other page from landing page, `useCurrentUser` hook will not invoke new GraphQL queries, thus not calling `onCompleted` callback at all.
This PR fixes the issue by using …

Fix current user missing in Google Analytics

---

pages/articles.js

This PR adds a URL param, `articleTypes`, to rumors-site article list.
- Currently we do not officially launch image support, so the UI of this filter is not implemented yet.
- Users must **manually specify `articleTypes` in URL**, it is not accessible from UI.
- `articleTypes` should be a comma separated list of `ArticleTypeEnum` (`TEXT`, `IMAGE`, `VIDEO`, `AUDIO`).
- When not given, `articleTypes` is not specified in `ListArticles`.
- If given, `articleTypes` is specified and thus would [override `MEDIA_ARTICLE_SUPPORT` flag in rumors-api](https://github.com/cofacts/rumors-api/blob/8eb18c6202be8735e5d7fe31db4fee5acd7eee06/src/graphql/queries/ListArticles.js#L513-L525).
The result depends on if the API has turned on `MEDIA_ARTICLE_SUPPORT` flag. On staging it is turned on, so it does not …

Add articleTypes URL param without UI

---

components/SideSection.js
components/SideSection.stories.js
components/__snapshots__/SideSection.stories.storyshot
pages/article/[id].js

Support image articles be displayed in the similar article section in article detail page.
Depends on API https://github.com/cofacts/rumors-api/pull/291
Mobile
Desktop
Mobile
Desktop

Support showing similar images in side section

---

components/ListPageDisplays/ArticleCard.js
components/ListPageDisplays/ListPageCards.stories.js
components/ListPageDisplays/ReplySearchItem.js
components/ListPageDisplays/__snapshots__/ListPageCards.stories.storyshot
components/NewReplySection/Mobile.js
components/ProfilePage/RepliedArticleTab.js
components/RelatedReplies.js
components/ReportPage/__snapshots__/ActionButton.stories.storyshot
components/SideSection.js
components/SideSection.stories.js
components/Thumbnail.js
components/__snapshots__/SideSection.stories.storyshot
pages/article/[id].js
pages/replies.js
pages/reply/[id].js

- Implements `Thumbnail` for thumbnail in list pages    
- "list pages" includes related articles, article list, reply list, reply search, and the search result of similar replies in reply editor. 
- It replaces `SideSectionImage` in `SideSection`, but is way more versatile than `SideSectionImage`
- It is designed to use thumbnail images only
- As we did not implement "thumbnail" variant for video and audio, "Preview not supported yet" will be shown.
- Note that the thumbnail may load if an logged in user get data via AJAX
- This is expected before we properly implement thumbnail generation.
- The thumbnail will show for logged in user getting data from AJAX is due to the `attachmentUrl` resolution logic -- it will resolve to `ORIGINAL`
- When the data is retrieved via server-side …

Support audio and video

---

components/ListPageControls/ArticleTypeFilter.js
components/ListPageControls/index.js
components/ProfilePage/RepliedArticleTab.js
i18n/zh_TW.po
pages/articles.js
pages/replies.js

Implements article type filter (URL param: `articleTypes`) for article list, reply list and profile page
- Implementation is very similar to [`ReplyTypeFilter`](https://github.com/cofacts/rumors-site/blob/master/components/ListPageControls/ReplyTypeFilter.js)
- Did not include search result page because currently we can only search by text, so results are all in text, no need to filter by article type
- Did not include hoax-for-you page for simplicity

Article type filter for Article list, Reply list and Profile page

---

i18n/zh_TW.po
pages/about.js

From: https://github.com/cofacts/rumors-site/issues/462
Add the introdeuction video in the about page. 
<image width="600" src="https://user-images.githubusercontent.com/43416399/197322713-1d7a399b-ea51-49e7-9a6e-8af0ada4d280.jpg"/>
<image height="300" src="https://user-images.githubusercontent.com/43416399/197322710-588dabb6-0b13-4c73-907d-4670160367ec.jpg"/>
<image width="600" src="https://user-images.githubusercontent.com/43416399/197322707-0d1d3096-a399-4054-92d1-729ea711de95.jpg"/>
<image height="300" src="https://user-images.githubusercontent.com/43416399/197322709-03650a28-abb7-4d00-846f-c74c8816317a.jpg"/>

feat: add intro video in about page

---

components/AppLayout/AppFooter.js
components/AppLayout/LoginModal.js
constants/urls.js
pages/terms.js

- Loads latest term from Github; updating term do _not_ require a rebuild and redeploy.
- Loads markdown parser and DOM sanitizer from CDN (so that it does not take space).
- Includes a link to Github for users to check the revision of this agreement

Implements terms page directly under Cofacts website

---

components/ListPageDisplays/__snapshots__/ListPageCards.stories.storyshot
components/Thumbnail.js

Fixes #511 
From doc:
> Without the `playsinline` attribute, videos must be in full-screen mode for playback on iPhone.
https://developer.apple.com/documentation/webkit/delivering_video_content_for_safari#3030250
This PR adds `playsinline` (camelCase in React) so that iOS don't automatically fullscreen the videos.
The branch has been deployed to https://dev.cofacts.tw for iOS users to test.
https://user-images.githubusercontent.com/108608/201179204-ebcb126e-7781-46c3-bf45-b170c5fd8318.mov

Fix iOS video fullscreen problem

---

components/Hyperlinks.js
components/__snapshots__/Hyperlinks.stories.storyshot
pages/article/[id].js

This PR implements block SEO spam M3 in the design doc https://g0v.hackmd.io/XBJS-KEtScWyVCuQ9P_iNQ?both#M3-Hide-blocked-article-for-non-logged-in-users
- [feat(article): add meta tag that blocks search engine for blocked articles](https://github.com/cofacts/rumors-site/commit/429ade7b0f2402274813936e8c3ad88ccd8b7a63) 
- [feat(article): add ugc rel for all article's hyperlinks](https://github.com/cofacts/rumors-site/commit/0b1b9d7d1ba9fbff9909c829714374c41a08eeaf)
-  [feat(article): hide blocked article for anonymous users](https://github.com/cofacts/rumors-site/commit/ac6ac02d109d16d9bab33fbefe8935d84bba8694)
Note that the robot meta tag is added

Block spammer articles

---

components/ReplyRequestReason/ReplyRequestReason.js
pages/article/[id].js

feat(article): don't show reply requests with <=0 score for users not logged in yet

---

components/AppLayout/AppFooter.js
i18n/zh_TW.po

adjust AppFooter

---

components/ActionMenu/ReportAbuseMenuItem.js
components/CreateReplyRequestForm/CreateReplyRequestForm.js
pages/article/[id].js

Implements [Anti-SEO spam M4](https://g0v.hackmd.io/XBJS-KEtScWyVCuQ9P_iNQ#M4-Allow-reporting-SEO-spammer-articles).
Not logged in: no change
Logged in:
Can submit:

feat(article): add report button to article detail

---

pages/article/[id].js

`articleUserId` is just used in reporting user, should not block page from rendering.
Fixes #531 
Before: https://cofacts.tw/article/5673777689453-rumor
After: https://dev.cofacts.tw/article/5673777689453-rumor

Don't throw error when article does not have ID

---

.env.sample
README.md
lib/gtm.ts
package-lock.json
package.json
pages/_document.js
pages/api/articles/[feed].js
pages/article/[id].js
pages/impact.js
pages/reply/[id].js

- [Removes universal-analytics](https://github.com/cofacts/rumors-site/commit/482c4279299b85e2f76ccbfdb08bad534b8301ac) and [PUBLIC_GA_TRACKING_ID](https://github.com/cofacts/rumors-site/commit/f9e6a1695538201dd72094840d2dac11df840cf3)
- We give up on tracking RSS polls because it's rarely analyzed.
- We remove `PUBLIC_GA_TRACKING_ID`, setup universal anaytics on GTM instead -- it's going to deprecate on July 1st anyway
- [Push doc to datalayer once on dataLoaded GTM event](https://github.com/cofacts/rumors-site/commit/84fa2b019d49c024a148b50c618e4b937725b103)
- So that we can setup GA4 events and send details of an article / reply in GTM

Remove universal analytics and send more data to dataLayer

---

components/AIReplySection.js
components/CurrentReplies.js
i18n/zh_TW.po
pages/article/[id].js

Depends on: cofacts/rumors-api#299
Design doc: https://g0v.hackmd.io/@cofacts/rd/%2F%40cofacts%2FrknFrmdk3
Figma: https://www.figma.com/file/DvmAQjMJCncuPORWKnljM1/Cofacts-LIFF-and-new-designs?node-id=5133-543&t=TpWZ8Az9Cmii59Qp-4
- Show AI reply in article page
- Automatically expand when no replies yet; collapse when has reply

Display AI reply

---

components/ListPageDisplays/ArticleCard.js
components/ListPageDisplays/__snapshots__/ListPageCards.stories.storyshot

- change the order of text and image
- add image right margin

UX improvements of images in article page

---

components/Collaborate/CollabEditor.js
components/Collaborate/CollabHistory.js
components/Collaborate/Prosemirror.css
components/Collaborate/Schema.js
i18n/zh_TW.po
package-lock.json
package.json

- Add CollabHistory component to display history in modalview
- Use [yjs-demos schema](https://github.com/yjs/yjs-demos/blob/main/prosemirror-versions/schema.js) for displaying `ychange`
- Refactor CollabEditor: use [use-prosemirror](https://github.com/ponymessenger/use-prosemirror) to create ProseMirror editor view
- HocuspocusProvider connects server onTranscribe and destroys(disconnects) when `Editor` unmount
- Make sure `Editor` and `CollabHistory` are created after provider synced, or ProseMirror editor may create with a wrong state
- Update ydoc user mapping with a json string contains id and name
- Note: there's another ProseMirror reactjs plugin [react-prosemirror](https://github.com/nytimes/react-prosemirror), but it require reactjs>=17
- …

Collaborative editing history

---

.github/workflows/build-and-push.yml

https://github.com/cofacts/rumors-site/actions/runs/6383563884/job/17325001224

ci: cloud run auto deploy

---

components/Collaborate/CollabEditor.js
components/Collaborate/CollabHistory.js
components/Collaborate/Prosemirror.css
components/Collaborate/Schema.js
package-lock.json
package.json

Fixes #550 
- Declare `code: true` on paragraph text, which [causes some commands to behave differently](https://prosemirror.net/docs/ref/#model.NodeSpec).
- Proof of concept codesandbox: https://codesandbox.io/s/codemirror-vn88l4?file=/src/index.mjs:678-750
- We keep `paragraph` because [prosemirror doc](https://prosemirror.net/docs/guide/#schema ) says that at least one child node in `nodes` that should block content.
- The block level serves backward compatibility
- Existing human-edited transcripts are made of multiple paragraphs + text
- new AI transcripts in [prosemirror-schema-basic](https://github.com/cofacts/rumors-api/blob/master/src/graphql/mutations/CreateMediaArticle.js#L11), which also defaults to one single paragraph, with other stuff that we don't need)
- The block level …

Fix collab editor line break disappear issue

---

README.md

Updated README to specify node v16 is required since node v21 had a number of errors
One error was:
- Had to fix an ERR_OSSL_EVP_UNSUPPORTED error with running ` npm run dev ` by doing `export NODE_OPTIONS=--openssl-legacy-provider ` as per this stackoverflow article: https://stackoverflow.com/questions/69394632/webpack-build-failing-with-err-ossl-evp-unsupported
Another error occurred when trying to accessing localhost:3000
``` ./node_modules/date-fns/locale/pt-BR/index.js.flow 4:7
Module parse failed: Unexpected token (4:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| // This file is generated automatically by `scripts/build/typings.js`. Please, don't change it.
|
> …
```

Updated README to specify node v16 is required since node v21 had a number of errors

---

components/Collaborate/CollabEditor.js

ref: https://g0v.hackmd.io/vKCvrqSQTlm7GEx9MAXGaw?view#op-Transcript-spam-%E8%99%95%E7%90%86
**normal user** 
**blocked user**

fix(collaborate): blocked user shouldn't be able to edit transcript

---

lib/__tests__/__snapshots__/text.tsx.snap
lib/__tests__/text.tsx
lib/text.tsx
package-lock.json
package.json

https://github.com/cofacts/rumors-site/issues/548

Use linkifyjs for better url extraction lgic

---

components/Hyperlinks.js

Solves #274.
Changes:
* When on mobile, and when then are two or more links, the links are displayed horizontally and can be scrolled horizontally.

Enhance display of many link previews

---

components/Hyperlinks.js
components/Infos/__snapshots__/Infos.stories.storyshot
components/ReportPage/__snapshots__/ActionButton.stories.storyshot
components/__snapshots__/Hyperlinks.stories.storyshot

Fix missing test update in https://github.com/cofacts/rumors-site/pull/571

fix(components): update snapshot due to css-in-js id change

---

components/CreateReplyRequestForm/CreateReplyRequestForm.js
components/ReplyRequestReason/ReplyRequestReason.js

added the header to the reply request!

Adding header

---

components/Thumbnail.tsx
typegen/gql.ts
typegen/graphql.ts

Current API on master branch actually cannot run `npm run typegen`. (see [discussion](https://github.com/dotansimha/graphql-code-generator/issues/8570#issuecomment-2381251752))
This PR fixes the issue by converting `Thumbnail` component to Typescript and define relevant types.

Fix type for codegen

---

pages/article/[id].js
pages/reply/[id].js

Fixes #577 as well as #570. In the end, `status` field is not required at all for replies; merely by looking at the status of original article reply, we can judge if the reply is blocked or not.
Not logged in: cannot see everything else
Logged in: can see and interact everything
Not logged in
Logged in

Reply detail and article detail revamp for blocked content

---

components/ProfilePage/ProfilePage.js
components/ProfilePage/UserPageHeader.js
i18n/zh_TW.po

Display join date of a user on their profile page #412 
In English
In Mandarin
Not sure whether putting JoinDate in that place is optimal for UI

feat(Profile page): show join date

---

components/ProfilePage/ProfilePage.js

I found that latestSlug returns null when the user hasn't set their slug yet. Therefore, I changed `latestSlug === undefined` to `!latestSlug && latestSlug !== ''`
Additionally, if the user resets their slug to an empty string, it will fail the condition. To address this, I changed the userId to ensure redirection leads to the user's page instead of "my" page.
able to see other user's profile page

fix(ProfilePage): should see other users' profile page

---

components/AppLayout/AppLayout.js
components/AppLayout/context.js
components/CreateReplyRequestForm/CreateReplyRequestForm.js

fix #277
This PR changes to show the login modal when the user is not logged in and the user wants to comment on an article.
I have done this with React Context instead of prop drilling.
I am not quite familiar with React, please let me know it there are any changes needed.

feat: show login modal when anonymous user clicks on comment btn

---

components/SearchPageJumbotron.js

fix #281 
As per requirements from the issue description, I have used `TextAreaAutoResize` component from Material UI. I have also adjusted the styles of the textarea since the text inside is overlapping with search icon button.
Before:
After:
I noticed pressing enter key on the current site https://cofacts.org/search did not trigger search, but I have added it as per the issue description.
I also adjusted the `Searching` text to stick at the top of the flex area.

feat: auto resize search bar
