cofacts/rumors-site

pages/index.js

index: refactor shorten_title and MAXIMUM_LENGTH into appropriate closure

---

components/App.js
components/CurrentReplies.js
components/Modal/index.js
pages/article.js
redux/articleDetail.js

Authors can delete and restore their own reply connections

---

.babelrc
components/AppFooter.js
components/AppHeader.js
components/ArticleItem.js
components/CurrentReplies.js
components/CurrentReplies.styles.js
components/RelatedReplies.js
components/ReplyForm.js
constants/replyType.js
constants/urls.js
package.json
pages/article.js
pages/index.js
postcss.config.js
yarn.lock

Fixes #22 , #28 
In order to enable shared style ( see https://github.com/cofacts/rumors-site/pull/31/files#diff-a166c852270284265979a9e66e367d36R8 ), we have to disable prostcss-nested and remove the deprecated style-jsx-postcss.

Add new reply type "opinionated" and adjust "not article" wordings

---

components/AppHeader.js
components/ArticleItem.js
components/CurrentReplies.js
components/ListItem.styles.js
components/Pagination.js
components/ReplyItem.js
constants/replyType.js
pages/index.js
pages/replies.js
redux/replyList.js

* 最上方加入切換 nav menu
* 顯示回應種類、作者、內容節錄、使用狀況、時間
* 藏起 logo、保留 nav menu
* 「只顯示我寫的」會藏起作者資訊（因為都是自己寫的）

Reply list appearance

---

components/AppHeader.js
components/RelatedReplies.js
package.json
pages/article.js
yarn.lock

- Add tooltip when the cursor hovers related articles.
- Add simple similarity in the header.

Add tooltip and simple similarity on related articles.

---

.travis.yml
README.md
package.json

Setup travis

---

components/App/AppFooter.js
components/App/AppHeader.js
constants/urls.js

Add tutorial link and email contact information to site header & footer

---

components/App/AppFooter.js
components/App/AppHeader.js
components/ReplyForm.js
constants/urls.js

- Replace some of the "Editor reference" link to Hackfoldr's link
- Replace the URL of "Editor reference" to its URL in hackfoldr

Add project hackfoldr links

---

.gitignore
components/ArticleItem.js
components/ListItem.styles.js
pages/article.js
pages/index.js
pages/replies.js

Try to improve SEO by head title and some HTML tags
close #52

SEO improve

---

ducks/articleList.js
pages/index.js

Filter by replyrequest count

---

ducks/replyDetail.js
pages/reply.js

fix #71  upvote / downvote in reply page

reply page vote fix #71

---

constants/replyType.js

{ label: '僅含失效連結', value: '訊息僅含有失效連結，無從查證。' },
=>
{ label: '無查證需要', value: '訊息與謠言查證無關。' },

adjust not article msg  label and value

---

pages/article.js

Because they might be the cause of "spammy markup"
Fixes #67

Removing ClaimReview tags for now

---

ducks/articleList.js

fix the wrong reducer because I ignore the cache strategy exists.
fix #96

fix articleList [LOAD] reducer for cache strategy

---

components/App/AppFooter.js
components/GoogleWebsiteTranslator/GoogleWebsiteTranslator.js
components/GoogleWebsiteTranslator/index.js
pages/article.js
pages/articles.js

add google website translator to article and articles page with position bottom right fixed

add google website translator to article and articles page

---

components/App/UserName.js
components/FullSiteArticleStats.js
ducks/auth.js
pages/articles.js

fix #98 [Gamification] Show overall progress bar 

---

components/FullSiteArticleStats.js

fix reply progress bar bug( PR#118)

---

server.js

Currently /tw is broken. This PR fixes this

Fix /tw route

---

components/ReplyRequestReason/ReplyRequestReason.js

Sorry~ I missed passing articleId to stateless component LinkAuthorList since previous refactor.

119 fix search user by article

---

components/App/UserName.js
components/EditorName.js
components/ReplyConnection.js
ducks/articleDetail.js
ducks/replyDetail.js
package-lock.json
package.json
pages/reply.js

fix #99 [Gamification] show level & the level name for each user when hovering on editor's name

---

server.js

`/workshop` redirect for 20181005 workshop

---

components/EditorName.js
package-lock.json
package.json

Use balloon-css instead of react-tooltip.

Fix #152 Level overlap

---

pages/reply.js

Fix `List of "articles with the same reply" is missing`

---

components/ReplyFeedback.js
components/ReplyFeedback.styles.js
ducks/articleDetail.js

https://github.com/cofacts/rumors-site/issues/120
Users can view reasons why a reply is downvoted by clicking "Why?" beside downvote count. 
- Default
- Downvote Reasons Modal
- If no downvote, do not show switch

Show reasons why a reply is downvoted

---

constants/replyType.js

add quick reply '連結失效'

---

.env.sample
README.md
components/AppLayout/AppLayout.js
components/LandingPage/Jumbotron.js
lib/gtm.js
pages/_document.js
pages/article/[id].js
pages/articles.js
pages/index.js
pages/reply/[id].js

This PR adds Google Tag Manager support.
- Google Tag Manager embedding snippet
- utility function to push to dataLayer: `lib/gtm.js`
- emits custom events like `routeChangeStart`, `routeChangeComplete`, and `dataLoaded` so that developers can build triggers on that

Google Tag Manager support

---

components/LandingPage/Jumbotron.js
pages/index.js

Fixing the CSS issue in mobile phone #135

Fix CSS in landing page

---

pages/index.js

the reason is qr-code png size less than url-loader limit setting, so it compile to base64.
use import to compile.

hi~ g0v Tainan great！

---

.env.sample
lib/stackimpact.js
package-lock.json
package.json
pages/_document.js

This PR adds stackimpact CPU time metrics integration.

Add stackimpact integration

---

components/UsedArticleItem.js

https://github.com/cofacts/rumors-site/issues/196

workaround for cannot read property 'name' of null

---

pages/articles.js

issue: #212 
Add an option to sort articles list by timestamp of the latest reply of the article.

Add new articles list sorting option

---

components/CreateReplyRequestDialog/CreateReplyRequestDialog.js
components/CreateReplyRequestDialog/index.js
pages/article/[id].js

add component "CreateReplyRequestDialog"

---

.babelrc.js
components/AppLayout/AppFooter.js
components/AppLayout/AppHeader.js
components/ArticleItem.js
components/ArticlePageLayout.js
components/ReplyFeedback.js
components/TimeRange.js
i18n/zh_TW.po
pages/articles.js
pages/replies.js

Translate to zh_TW of list pages, before pushing to production.
Translations referring to the [spec](https://g0v.hackmd.io/@NFi0czulSemxCM8RNSlz8Q/HJ8xT3QVU) and [mockup](https://www.figma.com/file/zpD45j8nqDB2XfA6m2QskO/Cofacts-website?node-id=0%3A1).

Traditional Chinese translation for list pages

---

package-lock.json
package.json

Ref: https://github.com/storybookjs/storybook/issues/10477#issuecomment-635075061
Reproduce:
1. `docker pull node:12`
2. `IMAGE_NAME=rumors-site-test hooks/build`
3. See build error like this one: 
This PR follows suggestions in https://github.com/storybookjs/storybook/issues/10477 to fix the build error.

Upgrade babel-preset-env to fix storybook build issue.

---

pages/article/[id].js

Fix article detail page layout

Fix flexbox width

---

components/ArticleCategories/AddCategoryDialog.js
components/ArticleCategories/ArticleCategories.js
components/ArticleCategories/ArticleCategory.js
components/ArticleCategories/CategoryOption.js

New design for article page category system, [mockup].(https://www.figma.com/file/zpD45j8nqDB2XfA6m2QskO/Cofacts-website?node-id=912%3A303)
some behaviors are still weird, just pop this version out to collect more feedbacks.

Improve article category UI

---

pages/article/[id].js

[Trivial] Fix trendline

---

components/ArticleCategories/ArticleCategory.js
components/ArticleCategories/CategoryOption.js
pages/article/[id].js

Add user id field to CreateArticleCategory

hotfix: add category bug

---

components/ListPageDisplays/ReplySearchItem.js

Fix [20200729 release blocker](https://g0v.hackmd.io/r3NK7xssSwCNPFxthlw7tA#%E2%9B%94%EF%B8%8F-Release-Blockers1).

Fix reply search release blocker

---

components/ArticlePageLayout.js
components/FeedDisplay.js
package-lock.json
package.json
pages/api/articles/[feed].js

Fixes #262 
feedUrl cannot handle options passed by ArticlePageLayout, so put option into query.

Fix 262 rss function

---

lib/theme.js

add cofacts colors as common colors in theme palette

---

components/AppLayout/Widgets/Avatar.js
components/ListPageControls/ArticleStatusFilter.js
components/ListPageControls/CategoryFilter.js
components/ListPageControls/LoadMore.js
components/ListPageControls/ReplyTypeFilter.js
components/ListPageControls/SortInput.js
components/ListPageControls/TimeRange.js
components/ListPageControls/index.js
components/ListPageDisplays/ReplyItem.js
components/ListPageDisplays/index.js
pages/articles.js
pages/hoax-for-you.js
pages/replies.js

This PR replaces `<ArticlePageLayout>` in `/articles`, `/hoax-for-you` and `/replies` with data loading logic & filter param processing. Each page now have their own logic in display & filter handling.
This is part of the "3rd PR"  mentioned in [Cofacts list page refactor](https://g0v.hackmd.io/h8rP0TOGTh2Clxi_Oi_QKw#%E8%A6%8F%E5%8A%83).
- `ListPageControls`
- Add `index.js` to enable `import {...} from 'components/ListPageControls'` syntax
- Components that stores state in URL params like `SortInput`, `ArticleStatusFilter`, `CategoryFilter`, `ReplyTypeFilter` and `TimeRange` components now expose `getValue(query)` or `getValues(query)` so that URL query read / write is encapsulated within components
- `LoadMore` now declares its own data dependency in exposed GraphQL fragments.
- This …

Remove ArticlePageLayout from /articles, /hoax-for-you and /replies

---

components/Subscribe/IFTTTItem.js

Figma : https://www.figma.com/file/zpD45j8nqDB2XfA6m2QskO/Cofacts-website?node-id=3146%3A351
Discussion : https://g0v.hackmd.io/GhVhBlK_QwKT3E5clAfkJw?view#Cofacts-Next-%E8%BF%BD%E8%B9%A4
1. Set `rel` to 0, so related videos will come from the same channel as the video that was just played.
2. Set `modestbranding` to 1 to hide YouTube logo which displays in the control bar.
Note : We can't hide the title and related videos now, YouTube `showinfo` parameter was [deprecated](https://developers.google.com/youtube/player_parameters#august-23,-2018).

[RSS] Implement new IFTTT UI

---

components/ListPageDisplays/ReplyItem.js

fix  https://github.com/cofacts/rumors-site/issues/265
createdAt is property of reply, not articleReply

fix reply time display bug

---

components/RelatedReplies.js

https://github.com/cofacts/rumors-site/issues/285
add reference in gql

fetch reference in reply

---

components/ProfilePage/UserPageHeader.js
i18n/zh_TW.po

- Provide automatic bio for `RUMORS_LINE_BOT` users
- So that the pseudonym and avatar doesn't confuse other editors

[Profile-03] Automatic chatbot user profile

---

components/NewReplySection/ReplyForm/ReferenceInput.js
i18n/zh_TW.po

Using IIFE to workaround in line 61-66 because of unknown translate `ttag` issue.

feat(ReferenceInput): #362 change text and translate

---

components/NewReplySection/ReplyForm/ReferenceInput.js
i18n/zh_TW.po

fix(ReferenceInput): wording fix

---

i18n/zh_TW.po
lib/terms.js

Copy-paste text is not affected.

Update terms to match suggestion from Lucien

---

package-lock.json
package.json

Update ttag babel plugin

---

components/ReportPage/SectionHowToUse.js
components/ReportPage/SectionInfluence.js
i18n/zh_TW.po

- wrap 'more' translation with ttag context
- handle influence background with media query

Impact page adjustment

---

components/ReportPage/SectionSponsor.js
constants/urls.js

Sponsor section URL

---

components/ProfilePage/AvatarSelector.js
components/ProfilePage/EditAvatarDialog.js

- add shuffle button to openpeeps editor
- fix anchor warning about conflicting props

edit-avatar touch up

---

components/ReportPage/SectionInfluence.js

New influence video URLs

---

components/ReportPage/EcosystemModal.js
components/ReportPage/SectionEcosystem.js
i18n/zh_TW.po
pages/impact.js

"| Cofacts" is _translated_ to irrelevant text
"| Cofacts" is normal now

Translate ecosystem modal

---

i18n/zh_TW.po

[Reply] chnage sidebar title to Similar replies

---

components/ReportPage/SectionFeatures.js
i18n/zh_TW.po

[Trivial] fix typo in ReportPage

---

components/ArticleCategories/AddCategoryDialog.js
components/ArticleCategories/ArticleCategories.js
pages/article/[id].js

it seem my prettier a bit different than the original project @_@

397 add sorted category for articles

---

components/NewReplySection/ReplyForm/ReasonEditor.js
package-lock.json

Fix editor RWD breakpoints #363

---

i18n/zh_TW.po

Discussion: https://g0v.hackmd.io/Syl8le5xS22nLo8Vc56gmw?both#Cofacts-search-snippet-%E4%BF%AE%E6%94%B9

Update landing page's Mandarin search snippet description

---

components/LandingPage/Header.js

#495 was merged to incorrect branch. This PR fixes the merge target and try again.

Retry #495

---

LEGAL.md

Facebook says that the current status does not comply with platform policy, but it would after we do it this way.

Insert contact email in privacy policy sections

---

components/CreateReplyRequestForm/CreateReplyRequestForm.js
pages/article/[id].js

輸入comment後，按submit(送出)，輸入comment的text field會隱藏縮起來。
如果comments有自己之前輸入的comment，comment(我想補充)會變成update comment(更新補充)。
如果comments有自己之前輸入的comment，按update comment(更新補充)會把之前輸入的comment text先置入text field。

adjust 'Make editing comments (reply requests) easier'

---

components/AppLayout/LoginModal.js

closes #427
- create the method to create provide style
- modify the color with Google sign-in button

feat: recolor google sign in btn

---

LEGAL.md

- CIB 討論：https://www.facebook.com/groups/cofacts/posts/3656817661216703/

List CIB as removal reason

---

components/CreateReplyRequestForm/CreateReplyRequestForm.js

feat: add login alert for comment click

---

components/AppLayout/AppFooter.js
i18n/zh_TW.po
pages/about.js

Reveal the relationship between the association and the community as discussed in https://g0v.hackmd.io/4HVFW0ivS-e9QfArzzOFiA#%E5%AF%A6%E7%A7%91%E5%8D%94%E6%9C%83

Add info about the association

---

i18n/zh_TW.po
pages/about.js

From https://g0v.hackmd.io/ucUXvnqbRBmsD6YGkmdYvg#%E5%8D%94%E6%9C%83

fix(about): update wording about ngo

---

components/ArticleReplyFeedbackControl/ReasonsDisplay.js

feedbacks with comments are sorted in the front

fix: feedbacks aren't sorted as expected

---

components/ArticleReply/ArticleReply.js
components/ArticleReply/ReplyShare.js
components/ArticleReplyFeedbackControl/ButtonGroupDisplay.js

fix #282 
fix component font size according to [spec]( https://www.figma.com/file/zpD45j8nqDB2XfA6m2QskO/Cofacts-website?node-id=681%3A0)
also adjust padding of the up/down vote buttons to make it looks a bit better when hovering
**mandarin**
**english**
**button group**

style(articleReply): fix reference title font size and share button size

---

components/LandingPage/SectionNews.js

- Add new English media coverage about Taiwan's fight against disinformation
- Add new Chinese language media coverage
- Maintain chronological order and consistent formatting
- Update coverage through early 2024

feat: Add new media coverage entries to SectionNews

---

components/ListPageControls/BaseFilterOption.tsx
components/ListPageControls/Filters.js
components/ReportPage/__snapshots__/ActionButton.stories.storyshot
i18n/zh_TW.po

Article filter dialog improvements

---

.github/workflows/ci.yml

Ref: https://github.com/actions/setup-node/issues/1275

fix: upgrade setup-node version to fix cache issue
